id: IA3C29D30
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:05:46+00:00'
last_modified: '2022-06-08T05:11:30.729696+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90019
  title: རྔ་བ་ཁུལ་ས་གནས་ལོ་རྒྱུས།（རྒྱ་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A1A1:
      image_group_id: I1PD90086
      title: Volume 1 of a ba zhou zhi
      total_pages: 1046
      order: 1
      base_file: A1A1.txt
    86B7:
      image_group_id: I1PD90087
      title: Volume 2 of a ba zhou zhi
      total_pages: 1054
      order: 2
      base_file: 86B7.txt
    E471:
      image_group_id: I1PD90088
      title: Volume 3 of a ba zhou zhi
      total_pages: 1070
      order: 3
      base_file: E471.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
